title: Minha Documentação
description: Documentação de exemplo com Just the Docs
remote_theme: just-the-docs/just-the-docs

footer_content: "© 2025 Minha Documentação - Todos os direitos reservados."
just_the_docs:
  logo: "/assets/images/logo.png"
  aux_links:
    "Meu Repositório no GitHub":
      - "https://github.com/SEU_REPO"